### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by safarishi** [shelleyp/LearningNode2#1]
When I try the example of code in `LearningNode2/chap3/example3-3.js`

I got the error of `Callback was already called`

ps: when the data directory only has one file it executes with no error, but when it has two file `data1.txt data2.txt` then it got the error

**Comment by shelleyp** [comment]
This is happening in the Async code, and only started with 6.2.2. I've filed an issue with Async, to see if there's an issue with my app, or their code. I'm thinking we hit some compatibility issue.

**Comment by safarishi** [comment]
Maybe, I am using the node version `v4.4.6`,and the error hit in the forEach, so it means that cannot use callback within forEach loop when you use aysnc module?

**Comment by shelleyp** [comment]
It works fine with Node 6.0.0 on Windows. It has always worked with Node 4.x. 

I have filed an issue with Async. I suspect they have an incompatibility with newest Node versions.

**Comment by shelleyp** [comment]
I'm assuming you're using a variation of Linux. 

Anyway, when I use my Windows machine, with 6.2.2 and older versions, it works. 

It used to work on my Linux/Ubuntu system. It doesn't now. 

Same V8 engine, same version of async. 

I'm beginning to suspect there's something in V8 that broke that differs between the two environments.

**Comment by shelleyp** [comment]
Folks at Async Github have stated I mixing the multiple files with single responses isn't something they would recommend. My bad on that. 

However it did work until 6.2.2 for me on Linux, and even now works on Windows, so I can't get you any other answer on why this code didn't work.

But if you do use Async, don't mix multiple response with single response callbacks. Again, that was my bad.

**Comment by safarishi** [comment]
Thank you for you answer.

the below is my system information
Linux lts 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Node version
v4.4.6
